apiVersion: v1
kind: Service
metadata:
  name: rag-backend-svc
  namespace: rag-ops-prod
spec:
  selector:
    app: rag-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP # Use LoadBalancer if on AWS/GCP